CC       := gcc
CXX      := g++
PYTORCH_PATH := $(HOME)/libtorch

# --- Preprocessor flags (includes, -D macros) ---
CPPFLAGS += -I$(PYTORCH_PATH)/include
CPPFLAGS += -I$(PYTORCH_PATH)/include/torch/csrc/api/include

# --- Compile flags ---
CFLAGS   := -O3 -std=gnu99 -Wall -MMD -MP
CXXFLAGS := -O3 -std=c++17 -Wall -MMD -MP

# --- Linker flags / libs ---
LDLIBS   := -lm -lpthread -fopenmp
TORCH_LIBS := -L$(PYTORCH_PATH)/lib -Wl,-rpath,$(PYTORCH_PATH)/lib -ltorch -ltorch_cpu -lc10

# --- Object list (kept from your link line) ---
OBJ := src/hgmt_lor_creator.o \
       src/hgmt_structs.o \
       src/linear_algebra.o \
       src/helper_functions.o \
       src/compton_chain_ordering.o \
       src/read_write.o \
       src/pore_geometry.o \
       neural_network/model_wrapper.o

# --- Final binary ---
hgmt_lor_creator: $(OBJ)
	$(CXX) -o $@ $(OBJ) $(TORCH_LIBS) $(LDLIBS)

# --- Compile rules (note: CPPFLAGS are passed) ---
%.o: %.c
	$(CC)  -c $(CPPFLAGS) $(CFLAGS)   $< -o $@

%.o: %.cc
	$(CXX) -c $(CPPFLAGS) $(CXXFLAGS) $< -o $@

# --- Auto deps generated by -MMD ---
-include $(OBJ:.o=.d)

.PHONY: clean
clean:
	rm -f $(OBJ) $(OBJ:.o=.d) hgmt_lor_creator

